-- Run this once in Supabase Dashboard -> SQL Editor.
-- The scraper writes with a secret/service-role key from the local .env file.

create table if not exists public.retailer_products (
    id bigint generated by default as identity primary key,
    site text not null check (site in ('nykaa', 'tira', 'amazon')),
    parent_product_id text not null default '',
    product_id text not null,
    sku text not null default '',
    gtin text not null default '',
    categories text[] not null default '{}',
    source_categories text[] not null default '{}',
    brand text not null default '',
    product_name text not null default '',
    variant text not null default '',
    mrp numeric(12, 2),
    selling_price numeric(12, 2),
    discount_pct numeric(7, 2),
    rating numeric(8, 5),
    rating_count bigint,
    review_count bigint,
    in_stock boolean,
    product_url text not null default '',
    image_url text not null default '',
    image_urls text[] not null default '{}',
    description text not null default '',
    description_html text not null default '',
    ingredients text not null default '',
    key_ingredients text[] not null default '{}',
    how_to_use text not null default '',
    key_features text[] not null default '{}',
    special_features text[] not null default '{}',
    product_attributes jsonb not null default '{}'::jsonb,
    rating_breakdown jsonb not null default '[]'::jsonb,
    top_reviews jsonb not null default '[]'::jsonb,
    scraped_at timestamptz not null,
    source_fingerprint text not null default '',
    detail_fingerprint text not null default '',
    first_seen_at timestamptz not null default now(),
    last_seen_at timestamptz not null default now(),
    last_checked_at timestamptz not null default now(),
    last_changed_at timestamptz not null default now(),
    last_detail_scraped_at timestamptz,
    detail_refresh_pending boolean not null default false,
    detail_unavailable boolean not null default false,
    last_seen_run_id uuid,
    missing_run_count integer not null default 0,
    is_active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint retailer_products_site_product_unique
        unique (site, product_id)
);

create table if not exists public.retailer_price_history (
    id bigint generated by default as identity primary key,
    site text not null check (site in ('nykaa', 'tira', 'amazon')),
    product_id text not null,
    parent_product_id text not null default '',
    sku text not null default '',
    variant text not null default '',
    mrp numeric(12, 2),
    selling_price numeric(12, 2),
    discount_pct numeric(7, 2),
    in_stock boolean,
    scraped_at timestamptz not null,
    created_at timestamptz not null default now(),
    constraint retailer_price_history_observation_unique
        unique (site, product_id, scraped_at)
);

create table if not exists public.retailer_scrape_runs (
    id uuid primary key default gen_random_uuid(),
    site text not null check (site in ('nykaa', 'tira')),
    status text not null default 'running'
        check (status in ('running', 'success', 'partial', 'failed')),
    started_at timestamptz not null default now(),
    finished_at timestamptz,
    products_seen integer not null default 0,
    products_new integer not null default 0,
    products_changed integer not null default 0,
    products_unchanged integer not null default 0,
    details_refreshed integer not null default 0,
    failures integer not null default 0,
    blocks integer not null default 0,
    requests integer not null default 0,
    message text not null default '',
    metadata jsonb not null default '{}'::jsonb
);

-- Safe upgrade path for databases created with an earlier schema.sql.
alter table public.retailer_products
    add column if not exists source_fingerprint text not null default '',
    add column if not exists detail_fingerprint text not null default '',
    add column if not exists first_seen_at timestamptz not null default now(),
    add column if not exists last_seen_at timestamptz not null default now(),
    add column if not exists last_checked_at timestamptz not null default now(),
    add column if not exists last_changed_at timestamptz not null default now(),
    add column if not exists last_detail_scraped_at timestamptz,
    add column if not exists detail_refresh_pending boolean not null default false,
    add column if not exists detail_unavailable boolean not null default false,
    add column if not exists last_seen_run_id uuid,
    add column if not exists missing_run_count integer not null default 0,
    add column if not exists is_active boolean not null default true;

create index if not exists retailer_products_brand_idx
    on public.retailer_products (lower(brand));

create index if not exists retailer_products_categories_gin_idx
    on public.retailer_products using gin (categories);

create index if not exists retailer_products_scraped_at_idx
    on public.retailer_products (scraped_at desc);

create index if not exists retailer_price_history_product_time_idx
    on public.retailer_price_history
    (site, product_id, scraped_at desc);

create index if not exists retailer_products_active_seen_idx
    on public.retailer_products (site, is_active, last_seen_at desc);

create index if not exists retailer_scrape_runs_site_started_idx
    on public.retailer_scrape_runs (site, started_at desc);

create or replace function public.finalize_retailer_scrape_run(
    p_site text,
    p_run_id uuid,
    p_inactive_threshold integer default 3
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
    affected integer;
begin
    update public.retailer_products
    set
        missing_run_count = missing_run_count + 1,
        is_active = (missing_run_count + 1) < greatest(1, p_inactive_threshold)
    where site = p_site
      and last_seen_run_id is distinct from p_run_id;
    get diagnostics affected = row_count;
    return affected;
end;
$$;

revoke all on function public.finalize_retailer_scrape_run(text, uuid, integer)
    from public, anon, authenticated;
grant execute on function public.finalize_retailer_scrape_run(text, uuid, integer)
    to service_role;

create or replace function public.set_retailer_product_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists retailer_products_set_updated_at
    on public.retailer_products;

create trigger retailer_products_set_updated_at
before update on public.retailer_products
for each row
execute function public.set_retailer_product_updated_at();

-- No browser/anonymous write policy is created. The local scraper uses the
-- secret/service-role key, which bypasses RLS. Never expose it in frontend.
alter table public.retailer_products enable row level security;
alter table public.retailer_price_history enable row level security;
alter table public.retailer_scrape_runs enable row level security;
